### ISSUE TITLE
The Lua engine is stuck in a error state for me, I can't basically edit anything

### ISSUE THREAD

**Issue by lifedoesgiveyoulemons** [zarroboogs/p4g-ct#1]
![Screenshot 2020-10-23 202437](https://user-images.githubusercontent.com/73363310/97045650-063a4500-156e-11eb-909b-e9e749362ec6.jpg)

**Comment by Pixelguin** [comment]
Do you have the data folder unzipped and in the same directory as the .CT file?

**Comment by lifedoesgiveyoulemons** [comment]
> Do you have the data folder unzipped and in the same directory as the .CT file?

so i have to unzip it and put it in the same directory, yes?

**Comment by lifedoesgiveyoulemons** [comment]
i have now unzipped it and put in same directory, the error doesnt show up now, hope it works it good as it's suppose to be, thx guys
